Added documentation
TaBSRest/GoFac pull request #10
Opened 2024-06-12 18:33 UTC by yuyoungKim

Add a document of setup guide

2024-06-12 20:06 UTC, yparkTaBS requested changes

2024-06-12 20:06 UTC, yparkTaBS commented on setupGuide.adoc
> +## [source, terminal]
pretty sure the syntax is wrong. GitHub can display adoc files. Please check and change.

2024-06-13 02:05 UTC, yparkTaBS approved these changes

2024-06-18 18:34 UTC, yparkTaBS submitted a review, later dismissed

2024-06-18 21:41 UTC, mokimokheonpark approved these changes
looks good

2024-06-19 14:45 UTC, closed without merging